<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../src/Core/Vec.fs" />
    <Compile Include="../src/Core/Domain.fs" />
    <Compile Include="../src/Core/Sim.fs" />
    <Compile Include="Check.fs" />
  </ItemGroup>
</Project>
